# Generated by Django 5.0.7 on 2024-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_quiz_quiz_option1_quiz_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default='null', max_length=50),
            preserve_default=False,
        ),
    ]
